apiVersion: v1
kind: Service
metadata:
  labels:
    application: demo3
  name: demo3
spec:
  selector:
    application: demo3
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo3
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: demo2
  namespace: default
- kind: ServiceAccount
  name: demo3
  namespace: default

